comment: false
codecov:
 token: 44db862b-db42-4a2e-a2f8-85f46c610a84
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        informational: true
    patch:
      default:
        target: auto
        threshold: 10%
        informational: true
